package vista;

import javax.swing.JFrame;
import controlador.PersonalDeCoordinacion;

public class _Vista_Listado_Tareas_MALA extends javax.swing.JFrame {

    public _Vista_Listado_Tareas_MALA(PersonalDeCoordinacion personalDeCoordinacion, JFrame vAnterior) {
        initComponents();
        
        this.personalDeCoordinacion = personalDeCoordinacion;
        this.vAnterior = vAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Listado_Tareas = new javax.swing.JPanel();
        jPanel_tareas = new javax.swing.JPanel();
        jLabel_listado_tareas = new javax.swing.JLabel();
        jLabel_tareas_sin_asignar = new javax.swing.JLabel();
        jScrollPane_listado_tareas = new javax.swing.JScrollPane();
        jList_listado_tareas = new javax.swing.JList<>();
        jScrollPane_tareas_sin_asignar = new javax.swing.JScrollPane();
        jList_tareas_sin_asignar = new javax.swing.JList<>();
        jLabel_nombre_equipo = new javax.swing.JLabel();
        jLabel_equipo = new javax.swing.JLabel();
        jLabel_personalDeEquipo = new javax.swing.JLabel();
        jButton_Atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listado Tareas");

        jPanel_Listado_Tareas.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_Listado_Tareas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel_tareas.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_tareas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_listado_tareas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_listado_tareas.setText("Listado de tareas");

        jLabel_tareas_sin_asignar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_tareas_sin_asignar.setText("Tareas sin asignar");

        jList_listado_tareas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jList_listado_tareas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane_listado_tareas.setViewportView(jList_listado_tareas);

        jList_tareas_sin_asignar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jList_tareas_sin_asignar.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane_tareas_sin_asignar.setViewportView(jList_tareas_sin_asignar);

        jLabel_nombre_equipo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel_nombre_equipo.setText("NOMBRE_EQUIPO");

        jLabel_equipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_equipo.setText("Equipo");

        jLabel_personalDeEquipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_personalDeEquipo.setText("Nombre Apellido Apellido");

        jButton_Atras.setBackground(new java.awt.Color(102, 0, 102));
        jButton_Atras.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton_Atras.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Atras.setText("ATRAS");
        jButton_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_tareasLayout = new javax.swing.GroupLayout(jPanel_tareas);
        jPanel_tareas.setLayout(jPanel_tareasLayout);
        jPanel_tareasLayout.setHorizontalGroup(
            jPanel_tareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tareasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_tareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_tareasLayout.createSequentialGroup()
                        .addGroup(jPanel_tareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_listado_tareas)
                            .addComponent(jScrollPane_listado_tareas, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(jPanel_tareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_tareas_sin_asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_tareas_sin_asignar)))
                    .addGroup(jPanel_tareasLayout.createSequentialGroup()
                        .addGroup(jPanel_tareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_tareasLayout.createSequentialGroup()
                                .addComponent(jLabel_equipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_nombre_equipo))
                            .addComponent(jLabel_personalDeEquipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Atras)))
                .addContainerGap())
        );
        jPanel_tareasLayout.setVerticalGroup(
            jPanel_tareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_tareasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_tareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_listado_tareas)
                    .addComponent(jLabel_tareas_sin_asignar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_tareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_listado_tareas, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addComponent(jScrollPane_tareas_sin_asignar))
                .addGap(72, 72, 72)
                .addGroup(jPanel_tareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Atras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_tareasLayout.createSequentialGroup()
                        .addComponent(jLabel_personalDeEquipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_tareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_equipo)
                            .addComponent(jLabel_nombre_equipo))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_Listado_TareasLayout = new javax.swing.GroupLayout(jPanel_Listado_Tareas);
        jPanel_Listado_Tareas.setLayout(jPanel_Listado_TareasLayout);
        jPanel_Listado_TareasLayout.setHorizontalGroup(
            jPanel_Listado_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Listado_TareasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_tareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_Listado_TareasLayout.setVerticalGroup(
            jPanel_Listado_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Listado_TareasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_tareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1148, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Listado_Tareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Listado_Tareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AtrasActionPerformed
        vAnterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_AtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Atras;
    private javax.swing.JLabel jLabel_equipo;
    private javax.swing.JLabel jLabel_listado_tareas;
    private javax.swing.JLabel jLabel_nombre_equipo;
    private javax.swing.JLabel jLabel_personalDeEquipo;
    private javax.swing.JLabel jLabel_tareas_sin_asignar;
    private javax.swing.JList<String> jList_listado_tareas;
    private javax.swing.JList<String> jList_tareas_sin_asignar;
    private javax.swing.JPanel jPanel_Listado_Tareas;
    private javax.swing.JPanel jPanel_tareas;
    private javax.swing.JScrollPane jScrollPane_listado_tareas;
    private javax.swing.JScrollPane jScrollPane_tareas_sin_asignar;
    // End of variables declaration//GEN-END:variables

    private PersonalDeCoordinacion personalDeCoordinacion;
    private javax.swing.JFrame vAnterior;
}
