package vista;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import controlador.PersonalDeProyecto;

public class Vista_1_Pers_Proyecto extends javax.swing.JFrame {

    public Vista_1_Pers_Proyecto(PersonalDeProyecto personalDeProyecto, JFrame vAnterior) {
        initComponents();
        this.personalDeProyecto = personalDeProyecto;
        this.vAnterior = vAnterior;
        this.jLabel_Nombre_Apellidos.setText(this.personalDeProyecto.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Personal_Coordinacion_jPanel = new javax.swing.JPanel();
        jLabel_Personal_Proyecto = new javax.swing.JLabel();
        jLabel_Nombre_Apellidos = new javax.swing.JLabel();
        btn_Salir = new javax.swing.JButton();
        btn_Consultar_Tareas_Asignadas = new javax.swing.JButton();
        btn_Chat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personal de Proyecto");
        setPreferredSize(new java.awt.Dimension(1146, 700));
        setResizable(false);

        Personal_Coordinacion_jPanel.setPreferredSize(new java.awt.Dimension(1100, 647));

        jLabel_Personal_Proyecto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Personal_Proyecto.setForeground(new java.awt.Color(102, 0, 102));
        jLabel_Personal_Proyecto.setText("Personal de Proyecto");

        jLabel_Nombre_Apellidos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Nombre_Apellidos.setText("Nombre Apellido Apellido");

        btn_Salir.setBackground(new java.awt.Color(102, 0, 102));
        btn_Salir.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_Salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_Salir.setText("SALIR");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        btn_Consultar_Tareas_Asignadas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_Consultar_Tareas_Asignadas.setText("Consultar Tareas Asignadas");
        btn_Consultar_Tareas_Asignadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Consultar_Tareas_AsignadasActionPerformed(evt);
            }
        });

        btn_Chat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_Chat.setText("- Chat -");
        btn_Chat.setEnabled(false);

        javax.swing.GroupLayout Personal_Coordinacion_jPanelLayout = new javax.swing.GroupLayout(Personal_Coordinacion_jPanel);
        Personal_Coordinacion_jPanel.setLayout(Personal_Coordinacion_jPanelLayout);
        Personal_Coordinacion_jPanelLayout.setHorizontalGroup(
            Personal_Coordinacion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Personal_Coordinacion_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Personal_Coordinacion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Personal_Proyecto)
                    .addComponent(jLabel_Nombre_Apellidos))
                .addGap(93, 93, 93))
            .addGroup(Personal_Coordinacion_jPanelLayout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addGroup(Personal_Coordinacion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Chat, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(btn_Consultar_Tareas_Asignadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        Personal_Coordinacion_jPanelLayout.setVerticalGroup(
            Personal_Coordinacion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Personal_Coordinacion_jPanelLayout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(btn_Consultar_Tareas_Asignadas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btn_Chat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addGroup(Personal_Coordinacion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Personal_Coordinacion_jPanelLayout.createSequentialGroup()
                        .addComponent(jLabel_Nombre_Apellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Personal_Proyecto)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Personal_Coordinacion_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Personal_Coordinacion_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        vAnterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_Consultar_Tareas_AsignadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Consultar_Tareas_AsignadasActionPerformed
        Vista_3_Tareas_Asignadas vista_Tareas_Asignadas = new Vista_3_Tareas_Asignadas(this.personalDeProyecto, this);
        vista_Tareas_Asignadas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Consultar_Tareas_AsignadasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Personal_Coordinacion_jPanel;
    private javax.swing.JButton btn_Chat;
    private javax.swing.JButton btn_Consultar_Tareas_Asignadas;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel_Nombre_Apellidos;
    private javax.swing.JLabel jLabel_Personal_Proyecto;
    // End of variables declaration//GEN-END:variables

    private PersonalDeProyecto personalDeProyecto;
    private javax.swing.JFrame vAnterior;
}
