package vista;

import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JList;
import java.util.ArrayList;

import data.DetallesActividad;
import data.DetallesTarea;
import controlador.PersonalDeCoordinacion;
import javax.swing.JOptionPane;

public class Vista_2_Actividad_Listado extends javax.swing.JFrame
{
    private ArrayList actividades; 
    
    public Vista_2_Actividad_Listado(PersonalDeCoordinacion personalDeCoordinacion, JFrame vAnterior) {
        initComponents();
        this.personalDeCoordinacion = personalDeCoordinacion;
        this.vAnterior = vAnterior;
        
        actividades = this.personalDeCoordinacion.consultarActividades();
        
        DefaultListModel listModel = new DefaultListModel();
        for(Object actividad: actividades){
            listModel.addElement(actividad);
        }
        this.jList_Actividades.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Actividades_Equipos = new javax.swing.JPanel();
        panel_Lista_Actividades = new javax.swing.JPanel();
        labelActividades = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList_Actividades = new javax.swing.JList<>();
        textField_Nombre_Actividad = new javax.swing.JTextField();
        label_Estado_Actividad = new javax.swing.JLabel();
        label_Estado_Actividad_valor = new javax.swing.JLabel();
        jBoton_Crear_Nueva_Actividad = new javax.swing.JButton();
        jButton_Editar_Actividad = new javax.swing.JButton();
        jButton_Duplicar_Actividad = new javax.swing.JButton();
        jButton_Atras = new javax.swing.JButton();
        ayuda_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actividades Listado");
        setResizable(false);

        jPanel_Actividades_Equipos.setBackground(new java.awt.Color(204, 204, 204));

        panel_Lista_Actividades.setBackground(new java.awt.Color(204, 204, 204));

        labelActividades.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelActividades.setText("Actividades");

        jList_Actividades.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jList_Actividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList_ActividadesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jList_Actividades);

        javax.swing.GroupLayout panel_Lista_ActividadesLayout = new javax.swing.GroupLayout(panel_Lista_Actividades);
        panel_Lista_Actividades.setLayout(panel_Lista_ActividadesLayout);
        panel_Lista_ActividadesLayout.setHorizontalGroup(
            panel_Lista_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Lista_ActividadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_Lista_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addGroup(panel_Lista_ActividadesLayout.createSequentialGroup()
                        .addComponent(labelActividades)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_Lista_ActividadesLayout.setVerticalGroup(
            panel_Lista_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_Lista_ActividadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelActividades)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        textField_Nombre_Actividad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        label_Estado_Actividad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Estado_Actividad.setForeground(new java.awt.Color(255, 0, 0));
        label_Estado_Actividad.setText("Estado de la actividad");

        label_Estado_Actividad_valor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_Estado_Actividad_valor.setForeground(new java.awt.Color(0, 204, 51));
        label_Estado_Actividad_valor.setText(" - - ");

        jBoton_Crear_Nueva_Actividad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBoton_Crear_Nueva_Actividad.setForeground(new java.awt.Color(0, 204, 51));
        jBoton_Crear_Nueva_Actividad.setText("Crear Nueva Actividad");
        jBoton_Crear_Nueva_Actividad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));
        jBoton_Crear_Nueva_Actividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoton_Crear_Nueva_ActividadActionPerformed(evt);
            }
        });

        jButton_Editar_Actividad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Editar_Actividad.setForeground(new java.awt.Color(0, 0, 255));
        jButton_Editar_Actividad.setText("Editar Actividad");
        jButton_Editar_Actividad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102)));
        jButton_Editar_Actividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Editar_ActividadActionPerformed(evt);
            }
        });

        jButton_Duplicar_Actividad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Duplicar_Actividad.setText("Duplicar Actividad");
        jButton_Duplicar_Actividad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));
        jButton_Duplicar_Actividad.setEnabled(false);

        jButton_Atras.setBackground(new java.awt.Color(102, 0, 102));
        jButton_Atras.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton_Atras.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Atras.setText("ATRAS");
        jButton_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AtrasActionPerformed(evt);
            }
        });

        ayuda_label.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ayuda_label.setText("Rellene el campo superior que será el Nombre de la Actividad al crear una Nueva Actividad");

        javax.swing.GroupLayout jPanel_Actividades_EquiposLayout = new javax.swing.GroupLayout(jPanel_Actividades_Equipos);
        jPanel_Actividades_Equipos.setLayout(jPanel_Actividades_EquiposLayout);
        jPanel_Actividades_EquiposLayout.setHorizontalGroup(
            jPanel_Actividades_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Actividades_EquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Actividades_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Actividades_EquiposLayout.createSequentialGroup()
                        .addComponent(panel_Lista_Actividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel_Actividades_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Actividades_EquiposLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(jPanel_Actividades_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBoton_Crear_Nueva_Actividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_Editar_Actividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_Duplicar_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel_Actividades_EquiposLayout.createSequentialGroup()
                                .addGroup(jPanel_Actividades_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_Actividades_EquiposLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel_Actividades_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textField_Nombre_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel_Actividades_EquiposLayout.createSequentialGroup()
                                                .addComponent(label_Estado_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(label_Estado_Actividad_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel_Actividades_EquiposLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(ayuda_label, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(52, Short.MAX_VALUE))))
                    .addGroup(jPanel_Actividades_EquiposLayout.createSequentialGroup()
                        .addComponent(jButton_Atras)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel_Actividades_EquiposLayout.setVerticalGroup(
            jPanel_Actividades_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Actividades_EquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Lista_Actividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Actividades_EquiposLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(textField_Nombre_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_Actividades_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Estado_Actividad)
                    .addComponent(label_Estado_Actividad_valor))
                .addGap(70, 70, 70)
                .addComponent(ayuda_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBoton_Crear_Nueva_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton_Editar_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton_Duplicar_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Actividades_Equipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Actividades_Equipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBoton_Crear_Nueva_ActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoton_Crear_Nueva_ActividadActionPerformed
        if(personalDeCoordinacion == null)
            JOptionPane.showMessageDialog(this, "! EL PERSONAL ES NULL");
        personalDeCoordinacion.altaNuevaActividad(" _ actividad nueva", "", null, null);
        this.actualizarListaActividades();
    }//GEN-LAST:event_jBoton_Crear_Nueva_ActividadActionPerformed

    private void jButton_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AtrasActionPerformed
        vAnterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_AtrasActionPerformed

    private void jButton_Editar_ActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Editar_ActividadActionPerformed
        int index = this.jList_Actividades.getSelectedIndex();
        if(index > -1){
            Object act = actividades.get(index);
            Vista_2_Actividad_Detalles proximaVentana = new Vista_2_Actividad_Detalles(
                    this.personalDeCoordinacion, //< contralador
                    this,                        //< ventana para volver
                    act,                         //< actividad a modificar
                    this.personalDeCoordinacion.consultarDetallesActividad(act) //< detalles de la actividad a modificar
            );
            proximaVentana.setVisible(true);
            this.setVisible(false);
        } else
            JOptionPane.showMessageDialog(this, "Actividad no selecciona");
    }//GEN-LAST:event_jButton_Editar_ActividadActionPerformed

    private void jList_ActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList_ActividadesMouseClicked
        int index = this.jList_Actividades.getSelectedIndex();
        if(index > -1){
            textField_Nombre_Actividad.setText(actividades.get(index).toString());
            Object act = actividades.get(index);
            
            String estadoActividad =  this.personalDeCoordinacion.consultarDetallesActividad(act).estadoActividad;
            label_Estado_Actividad_valor.setText(estadoActividad);
        }         
    }//GEN-LAST:event_jList_ActividadesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ayuda_label;
    private javax.swing.JButton jBoton_Crear_Nueva_Actividad;
    private javax.swing.JButton jButton_Atras;
    private javax.swing.JButton jButton_Duplicar_Actividad;
    private javax.swing.JButton jButton_Editar_Actividad;
    private javax.swing.JList<String> jList_Actividades;
    private javax.swing.JPanel jPanel_Actividades_Equipos;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelActividades;
    private javax.swing.JLabel label_Estado_Actividad;
    private javax.swing.JLabel label_Estado_Actividad_valor;
    private javax.swing.JPanel panel_Lista_Actividades;
    private javax.swing.JTextField textField_Nombre_Actividad;
    // End of variables declaration//GEN-END:variables

    private PersonalDeCoordinacion personalDeCoordinacion;
    private javax.swing.JFrame vAnterior;
    
    
    
    
    
    
    /*
    *    - FUNCIoNES AÑADIDAS EN LA VISTA 
    *    - (no coimplica que se hayan añadido de más en los modelos/controladores)
    */
    
    private void actualizarListaActividades(){
        jList_Actividades.removeAll();
        DefaultListModel modeloLista = new DefaultListModel();
       
        ArrayList actividades = personalDeCoordinacion.consultarActividades();
        for (Object actividad: actividades) {
            String nombre = personalDeCoordinacion.consultarDetallesActividad(actividad).nombre;
            modeloLista.addElement(nombre);
        }
        jList_Actividades.setModel(modeloLista);
    }

    private void vaciar(JList<String> lista) {
        lista.setModel(new DefaultListModel());
    }

    /*
    private void actualizarListaTareas() {
        listaActividades.removeAll();
        DefaultListModel modeloLista = new DefaultListModel();
       
        ArrayList tareas = personalDeCoordinacion.consultarTareas();
        for (Object tarea: tareas) {
            String nombre = personalDeCoordinacion.consultarDetallesTarea(tarea).nombre;
            modeloLista.addElement(nombre);
        }
        listaTareas.setModel(modeloLista);
    }
    */
/*
    private void vaciar(JComboBox<String> comboBox) {
        comboBox.setModel(new DefaultComboBoxModel());
    }
*/
    /*
    // obtener miembros del equipo seleccionado y poner en la lista de responsables
    private void actualizarMiembrosEquipo(Object equipo) {
        ArrayList miembros = personalDeCoordinacion.consultarMiembrosDelEquipo(equipo);
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        for(Object miembro: miembros){
            String nombre = personalDeCoordinacion.getNombrePersProy(miembro);
            dcbm.addElement(nombre);
        }
        this.comboBox_Responsable.setModel(dcbm);
    }
    */

    public void refrescar_lista_actividades() {
        actividades = this.personalDeCoordinacion.consultarActividades();
        DefaultListModel listModel = new DefaultListModel();
        for(Object actividad: actividades){
            listModel.addElement(actividad);
        }
        this.jList_Actividades.setModel(listModel);
    }
}
