package vista;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import controlador.PersonalDeCoordinacion;
import data.DetallesTarea;

public class Vista_3_Tarea_Editar extends javax.swing.JFrame
{
    final PersonalDeCoordinacion personalDeCoordinacion;
    final Vista_2_Actividad_Detalles vAnterior;
    final Object tarea;
    final DetallesTarea detallesTarea;
    
    public Vista_3_Tarea_Editar(PersonalDeCoordinacion personalDeCoordinacion, Vista_2_Actividad_Detalles vAnterior, Object tarea, DetallesTarea detallesTarea) {
        initComponents();
        this.personalDeCoordinacion = personalDeCoordinacion;
        this.vAnterior = vAnterior;
        this.tarea = tarea;
        this.detallesTarea = detallesTarea;
        
        carga_combo_box(responsable_combo, this.personalDeCoordinacion.consultarMiembrosDelEquipo(detallesTarea.equipo));
        
        textField_Nombre_Tarea.setText(detallesTarea.nombre);
        equipo_field.setText(detallesTarea.equipo.toString());
        jDate_fecha_max.setDate(detallesTarea.fechaMaxRealizacion);
        responsable_combo.setSelectedItem(detallesTarea.responsable.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Actividades = new javax.swing.JPanel();
        label_Editar_Tarea = new javax.swing.JLabel();
        textField_Nombre_Tarea = new javax.swing.JTextField();
        label_Fecha_Maxima_Realizacion_Tarea = new javax.swing.JLabel();
        jDate_fecha_max = new com.toedter.calendar.JDateChooser();
        label_Equipo = new javax.swing.JLabel();
        equipo_field = new javax.swing.JTextField();
        jLabel_Responsable = new javax.swing.JLabel();
        responsable_combo = new javax.swing.JComboBox<>();
        jButton_Modificar_Tarea = new javax.swing.JButton();
        jButton_Eliminar_Tarea = new javax.swing.JButton();
        jButton_Atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actividad Detalles");
        setResizable(false);

        panel_Actividades.setBackground(new java.awt.Color(255, 255, 255));

        label_Editar_Tarea.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_Editar_Tarea.setText("Editar Tarea");

        textField_Nombre_Tarea.setEditable(false);
        textField_Nombre_Tarea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textField_Nombre_Tarea.setForeground(new java.awt.Color(0, 153, 51));

        label_Fecha_Maxima_Realizacion_Tarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Fecha_Maxima_Realizacion_Tarea.setText("Fecha Maxima Realizacion");

        label_Equipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Equipo.setText("Equipo");

        equipo_field.setEditable(false);

        jLabel_Responsable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Responsable.setText("Responsable");

        jButton_Modificar_Tarea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Modificar_Tarea.setForeground(new java.awt.Color(0, 0, 255));
        jButton_Modificar_Tarea.setText("Modificar Tarea");
        jButton_Modificar_Tarea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));
        jButton_Modificar_Tarea.setMaximumSize(new java.awt.Dimension(125, 27));
        jButton_Modificar_Tarea.setMinimumSize(new java.awt.Dimension(125, 27));
        jButton_Modificar_Tarea.setPreferredSize(new java.awt.Dimension(125, 27));
        jButton_Modificar_Tarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Modificar_TareaActionPerformed(evt);
            }
        });

        jButton_Eliminar_Tarea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton_Eliminar_Tarea.setForeground(new java.awt.Color(255, 0, 0));
        jButton_Eliminar_Tarea.setText("Eliminar Tarea");
        jButton_Eliminar_Tarea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));
        jButton_Eliminar_Tarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Eliminar_TareaActionPerformed(evt);
            }
        });

        jButton_Atras.setBackground(new java.awt.Color(102, 0, 102));
        jButton_Atras.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton_Atras.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Atras.setText("ATRAS");
        jButton_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ActividadesLayout = new javax.swing.GroupLayout(panel_Actividades);
        panel_Actividades.setLayout(panel_ActividadesLayout);
        panel_ActividadesLayout.setHorizontalGroup(
            panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ActividadesLayout.createSequentialGroup()
                .addGroup(panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ActividadesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Editar_Tarea)
                            .addComponent(jButton_Atras)))
                    .addGroup(panel_ActividadesLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_Responsable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(responsable_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(equipo_field))
                            .addComponent(label_Fecha_Maxima_Realizacion_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDate_fecha_max, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_ActividadesLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButton_Modificar_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Eliminar_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_ActividadesLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(textField_Nombre_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        panel_ActividadesLayout.setVerticalGroup(
            panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ActividadesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label_Editar_Tarea)
                .addGap(55, 55, 55)
                .addComponent(textField_Nombre_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(label_Equipo)
                .addGap(13, 13, 13)
                .addComponent(equipo_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Responsable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(responsable_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_Fecha_Maxima_Realizacion_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDate_fecha_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Modificar_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Eliminar_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Actividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Actividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AtrasActionPerformed
        this.vAnterior.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton_AtrasActionPerformed

    private void jButton_Modificar_TareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Modificar_TareaActionPerformed
        if(textField_Nombre_Tarea.getText().equals(""))
            JOptionPane.showMessageDialog(this, "Debes rellenar el nombre");
        else{
            this.personalDeCoordinacion.modificarTarea(this.jDate_fecha_max.getDate(),detallesTarea.equipo, this.responsable_combo.getSelectedItem(),this.tarea);
            this.irAnteriorConRecarga();
            JOptionPane.showMessageDialog(this, "Tarea Modificada. Se mantiene el Nombre de la Tarea");
        }
    }//GEN-LAST:event_jButton_Modificar_TareaActionPerformed

    private void jButton_Eliminar_TareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Eliminar_TareaActionPerformed
        this.personalDeCoordinacion.eliminarTarea(tarea);
        JOptionPane.showMessageDialog(this, "Eliminando Tarea '" + tarea.toString() + "'."
                + "\nTareas En Cruso no serán eliminadas");
        this.irAnteriorConRecarga();
    }//GEN-LAST:event_jButton_Eliminar_TareaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField equipo_field;
    private javax.swing.JButton jButton_Atras;
    private javax.swing.JButton jButton_Eliminar_Tarea;
    private javax.swing.JButton jButton_Modificar_Tarea;
    private com.toedter.calendar.JDateChooser jDate_fecha_max;
    private javax.swing.JLabel jLabel_Responsable;
    private javax.swing.JLabel label_Editar_Tarea;
    private javax.swing.JLabel label_Equipo;
    private javax.swing.JLabel label_Fecha_Maxima_Realizacion_Tarea;
    private javax.swing.JPanel panel_Actividades;
    private javax.swing.JComboBox<String> responsable_combo;
    private javax.swing.JTextField textField_Nombre_Tarea;
    // End of variables declaration//GEN-END:variables


    private void carga_combo_box(JComboBox<String> comboBox, ArrayList array) {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for(Object object: array){
            modelo.addElement(object);
        }
        comboBox.setModel(modelo);
    }
    
    private void irAnteriorConRecarga() {
        Vista_2_Actividad_Detalles vActividades =(Vista_2_Actividad_Detalles) this.vAnterior;
        vActividades.actualizarListaTareas();
        this.vAnterior.setVisible(true);
        this.setVisible(false);
    }
}
