package vista;

import javax.swing.JOptionPane;
import controlador.GestorPrincipal;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import controlador.PersonalDeCoordinacion;
import controlador.PersonalDeProyecto;

public class Vista_0_Principal extends javax.swing.JFrame
{
    public Vista_0_Principal() {
        initComponents();
        gestorPrincipal = new GestorPrincipal();
        
        personal_De_Coordinacion =  (PersonalDeCoordinacion) gestorPrincipal.iniciar("PersonalDeCoordinacion");
        personal_De_Proyecto =  (PersonalDeProyecto) gestorPrincipal.iniciar("PersonalDeProyecto");
        
        radioBtn_Personal_De_Coordinacion.setSelected(true);
        buttonGroup_Tipo_Usuario.add(radioBtn_Personal_De_Coordinacion);
        buttonGroup_Tipo_Usuario.add(radioBtn_Personal_De_Proyecto);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Tipo_Usuario = new javax.swing.ButtonGroup();
        jLabel_Girls = new javax.swing.JLabel();
        jLabel_for = new javax.swing.JLabel();
        jLabel_Stem = new javax.swing.JLabel();
        jPanel_Tipo_Usuario = new javax.swing.JPanel();
        radioBtn_Personal_De_Coordinacion = new javax.swing.JRadioButton();
        radioBtn_Personal_De_Proyecto = new javax.swing.JRadioButton();
        jButton_Login = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GIRLS 4 STEM . v2.1.0");
        setPreferredSize(new java.awt.Dimension(1146, 700));
        setResizable(false);

        jLabel_Girls.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_Girls.setFont(new java.awt.Font("Consolas", 0, 120)); // NOI18N
        jLabel_Girls.setForeground(new java.awt.Color(102, 102, 255));
        jLabel_Girls.setText("Girls");
        jLabel_Girls.setAlignmentY(0.0F);

        jLabel_for.setFont(new java.awt.Font("Consolas", 0, 120)); // NOI18N
        jLabel_for.setForeground(new java.awt.Color(153, 0, 255));
        jLabel_for.setText("4");
        jLabel_for.setAlignmentY(0.0F);

        jLabel_Stem.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_Stem.setFont(new java.awt.Font("Consolas", 0, 120)); // NOI18N
        jLabel_Stem.setForeground(new java.awt.Color(102, 102, 255));
        jLabel_Stem.setText("STEM");
        jLabel_Stem.setAlignmentY(0.0F);

        jPanel_Tipo_Usuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 10, true));

        radioBtn_Personal_De_Coordinacion.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        radioBtn_Personal_De_Coordinacion.setText("Personal de Coordinacion");
        radioBtn_Personal_De_Coordinacion.setBorder(null);
        radioBtn_Personal_De_Coordinacion.setBorderPainted(true);

        radioBtn_Personal_De_Proyecto.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        radioBtn_Personal_De_Proyecto.setText("Personal De Proyecto");
        radioBtn_Personal_De_Proyecto.setBorder(null);
        radioBtn_Personal_De_Proyecto.setBorderPainted(true);

        jButton_Login.setBackground(new java.awt.Color(102, 0, 102));
        jButton_Login.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButton_Login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Login.setText("ENTRAR");
        jButton_Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Tipo_UsuarioLayout = new javax.swing.GroupLayout(jPanel_Tipo_Usuario);
        jPanel_Tipo_Usuario.setLayout(jPanel_Tipo_UsuarioLayout);
        jPanel_Tipo_UsuarioLayout.setHorizontalGroup(
            jPanel_Tipo_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Tipo_UsuarioLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel_Tipo_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Tipo_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioBtn_Personal_De_Coordinacion, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Tipo_UsuarioLayout.createSequentialGroup()
                            .addComponent(radioBtn_Personal_De_Proyecto)
                            .addGap(36, 36, 36)))
                    .addGroup(jPanel_Tipo_UsuarioLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        jPanel_Tipo_UsuarioLayout.setVerticalGroup(
            jPanel_Tipo_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Tipo_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioBtn_Personal_De_Coordinacion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radioBtn_Personal_De_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SALIR");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208)
                        .addComponent(jPanel_Tipo_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel_Girls, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_for, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Stem)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel_for, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Girls, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Stem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel_Tipo_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
        /* if(getSelectedButton().equals("Personal de Coordinacion"))
        {
        if(getSelectedButton().equals("Personal de Equipo")){
        } */
        
        if(radioBtn_Personal_De_Coordinacion.isSelected())
        {
            Vista_1_Pers_Coordinacion personal = new Vista_1_Pers_Coordinacion(personal_De_Coordinacion, this);
            personal.setVisible(true);
            this.setVisible(false);
        }
        else if(radioBtn_Personal_De_Proyecto.isSelected())
        {
            Vista_1_Pers_Proyecto personal = new Vista_1_Pers_Proyecto(personal_De_Proyecto, this);
            personal.setVisible(true);
            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "Elige algo");
        }
    }//GEN-LAST:event_jButton_LoginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_0_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_0_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_0_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_0_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new Vista_0_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Tipo_Usuario;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Login;
    private javax.swing.JLabel jLabel_Girls;
    private javax.swing.JLabel jLabel_Stem;
    private javax.swing.JLabel jLabel_for;
    private javax.swing.JPanel jPanel_Tipo_Usuario;
    private javax.swing.JRadioButton radioBtn_Personal_De_Coordinacion;
    private javax.swing.JRadioButton radioBtn_Personal_De_Proyecto;
    // End of variables declaration//GEN-END:variables
    
    String getSelectedButton() {
        for (Enumeration<AbstractButton> buttons = buttonGroup_Tipo_Usuario.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected())
                    return button.getText();
        } return null;
    }
    
    final GestorPrincipal gestorPrincipal;
    final PersonalDeCoordinacion personal_De_Coordinacion;
    final PersonalDeProyecto personal_De_Proyecto;
}
