package vista;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import controlador.PersonalDeCoordinacion;

public class Vista_1_Pers_Coordinacion extends javax.swing.JFrame {

    public Vista_1_Pers_Coordinacion(PersonalDeCoordinacion personalDeCoordinacion, JFrame vAnterior) {
        initComponents();
        this.personalDeCoordinacion = personalDeCoordinacion;
        this.vAnterior = vAnterior;
        this.jLabel_Nombre_Apellidos.setText(this.personalDeCoordinacion.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Personal_Coordinacion_jPanel = new javax.swing.JPanel();
        jLabel_Personal_Coordinacion = new javax.swing.JLabel();
        jLabel_Nombre_Apellidos = new javax.swing.JLabel();
        btn_Salir = new javax.swing.JButton();
        btn_Gestionar_Usuarios = new javax.swing.JButton();
        btn_Gestionar_Equipos = new javax.swing.JButton();
        btn_Consultar_Actividades = new javax.swing.JButton();
        btn_Chat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personal de Coordinacion");
        setPreferredSize(new java.awt.Dimension(1146, 700));
        setResizable(false);

        Personal_Coordinacion_jPanel.setPreferredSize(new java.awt.Dimension(1100, 647));

        jLabel_Personal_Coordinacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Personal_Coordinacion.setForeground(new java.awt.Color(102, 0, 102));
        jLabel_Personal_Coordinacion.setText("Personal de Coordinacion");

        jLabel_Nombre_Apellidos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Nombre_Apellidos.setText("Nombre Apellido Apellido");

        btn_Salir.setBackground(new java.awt.Color(102, 0, 102));
        btn_Salir.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_Salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_Salir.setText("SALIR");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        btn_Gestionar_Usuarios.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_Gestionar_Usuarios.setText("Gestionar Usuarios");
        btn_Gestionar_Usuarios.setEnabled(false);
        btn_Gestionar_Usuarios.setPreferredSize(new java.awt.Dimension(120, 30));

        btn_Gestionar_Equipos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_Gestionar_Equipos.setText("Gestionar Equipos");
        btn_Gestionar_Equipos.setEnabled(false);
        btn_Gestionar_Equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Gestionar_EquiposActionPerformed(evt);
            }
        });

        btn_Consultar_Actividades.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_Consultar_Actividades.setForeground(new java.awt.Color(0, 0, 153));
        btn_Consultar_Actividades.setText("Consultar Actividades");
        btn_Consultar_Actividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Consultar_ActividadesActionPerformed(evt);
            }
        });

        btn_Chat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_Chat.setText("- Chat -");
        btn_Chat.setEnabled(false);

        javax.swing.GroupLayout Personal_Coordinacion_jPanelLayout = new javax.swing.GroupLayout(Personal_Coordinacion_jPanel);
        Personal_Coordinacion_jPanel.setLayout(Personal_Coordinacion_jPanelLayout);
        Personal_Coordinacion_jPanelLayout.setHorizontalGroup(
            Personal_Coordinacion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Personal_Coordinacion_jPanelLayout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addGroup(Personal_Coordinacion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Consultar_Actividades, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(btn_Gestionar_Equipos, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(btn_Chat, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(btn_Gestionar_Usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
                .addContainerGap(396, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Personal_Coordinacion_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Personal_Coordinacion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Personal_Coordinacion)
                    .addComponent(jLabel_Nombre_Apellidos))
                .addGap(46, 46, 46))
        );
        Personal_Coordinacion_jPanelLayout.setVerticalGroup(
            Personal_Coordinacion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Personal_Coordinacion_jPanelLayout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(Personal_Coordinacion_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Personal_Coordinacion_jPanelLayout.createSequentialGroup()
                        .addComponent(btn_Gestionar_Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Gestionar_Equipos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Consultar_Actividades, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btn_Chat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(jLabel_Nombre_Apellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Personal_Coordinacion))
                    .addComponent(btn_Salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Personal_Coordinacion_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Personal_Coordinacion_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        vAnterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_Gestionar_EquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Gestionar_EquiposActionPerformed
        Vista_Equipos vista_Panel_Equipos = new Vista_Equipos(this.personalDeCoordinacion, this);
        vista_Panel_Equipos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Gestionar_EquiposActionPerformed

    private void btn_Consultar_ActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Consultar_ActividadesActionPerformed
        //this.actualizarListaActividades();
        Vista_2_Actividad_Listado vista_Actividades = new Vista_2_Actividad_Listado(this.personalDeCoordinacion, this);
        vista_Actividades.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_Consultar_ActividadesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Personal_Coordinacion_jPanel;
    private javax.swing.JButton btn_Chat;
    private javax.swing.JButton btn_Consultar_Actividades;
    private javax.swing.JButton btn_Gestionar_Equipos;
    private javax.swing.JButton btn_Gestionar_Usuarios;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel_Nombre_Apellidos;
    private javax.swing.JLabel jLabel_Personal_Coordinacion;
    // End of variables declaration//GEN-END:variables

    private PersonalDeCoordinacion personalDeCoordinacion;
    private javax.swing.JFrame vAnterior;
}
