package vista;

import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import java.util.ArrayList;
import data.DetallesActividad;
import data.DetallesTarea;
import controlador.PersonalDeCoordinacion;
import javax.swing.JOptionPane;

public class Vista_2_Actividad_Detalles extends javax.swing.JFrame
{
    private SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
    private PersonalDeCoordinacion personalDeCoordinacion;
    private javax.swing.JFrame vAnterior;
    private DetallesActividad detallesActividad;
    private Object actividad;
    private ArrayList tareas;
    
    public Vista_2_Actividad_Detalles(PersonalDeCoordinacion personalDeCoordinacion, JFrame vAnterior, Object actividad, DetallesActividad detallesActividad) {
        initComponents();
        this.personalDeCoordinacion = personalDeCoordinacion;
        this.vAnterior = vAnterior;
        this.actividad = actividad;
        this.detallesActividad = detallesActividad;
        this.panel_Tareas.setVisible(false);
        
        this.textField_Nombre_Actividad.setText(detallesActividad.nombre);
        this.textArea_Descripcion.setText(detallesActividad.descripcion);
        this.jDate_fecha_inicio.setDate(detallesActividad.fechaInicio);
        this.jDate_fecha_final.setDate(detallesActividad.fechaFin);
        this.estado_Actividad_Indicador.setText(detallesActividad.estadoActividad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Actividades_Equipos = new javax.swing.JPanel();
        panel_Actividades = new javax.swing.JPanel();
        labelActividades = new javax.swing.JLabel();
        jButton_Modificar_Actividad = new javax.swing.JButton();
        jButton_Eliminar_Actividad = new javax.swing.JButton();
        label_Estado_Actividad = new javax.swing.JLabel();
        estado_Actividad_Indicador = new javax.swing.JLabel();
        jDate_fecha_final = new com.toedter.calendar.JDateChooser();
        jDate_fecha_inicio = new com.toedter.calendar.JDateChooser();
        label_Fecha_Inicio = new javax.swing.JLabel();
        jLabel_Fecha_Final = new javax.swing.JLabel();
        jScrollPane_Descripcion = new javax.swing.JScrollPane();
        textArea_Descripcion = new javax.swing.JTextArea();
        textField_Nombre_Actividad = new javax.swing.JTextField();
        label_Descripcion = new javax.swing.JLabel();
        label_Nombre_Actividad = new javax.swing.JLabel();
        jButton_Iniciar_Actividad = new javax.swing.JButton();
        jButton_Atras = new javax.swing.JButton();
        consultar_tareas = new javax.swing.JButton();
        panel_Tareas = new javax.swing.JPanel();
        labelTareas = new javax.swing.JLabel();
        panel__Lista_Tareas = new javax.swing.JScrollPane();
        lista_tareas = new javax.swing.JList<>();
        label_Nombre_Tarea = new javax.swing.JLabel();
        textField_Nombre_Tarea = new javax.swing.JTextField();
        label_Equipo = new javax.swing.JLabel();
        jLabel_Responsable = new javax.swing.JLabel();
        label_Fecha_Maxima_Realizacion_Tarea = new javax.swing.JLabel();
        label_Fecha_Finalizacion_Real_Tarea = new javax.swing.JLabel();
        jButton_Modificar_Tarea = new javax.swing.JButton();
        jButton_Eliminar_Tarea = new javax.swing.JButton();
        jButton_Crear_Tarea_Nueva = new javax.swing.JButton();
        textField_Equipo = new javax.swing.JTextField();
        textField_Responsable = new javax.swing.JTextField();
        textField_FechaMax = new javax.swing.JTextField();
        textField_FechaFinTarea = new javax.swing.JTextField();
        label_Estado_Tarea = new javax.swing.JLabel();
        estado_Tarea_Indicador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actividad Detalles");
        setPreferredSize(new java.awt.Dimension(1146, 700));
        setResizable(false);

        panel_Actividades.setBackground(new java.awt.Color(255, 255, 255));

        labelActividades.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelActividades.setText("Actividad");

        jButton_Modificar_Actividad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Modificar_Actividad.setForeground(new java.awt.Color(0, 0, 255));
        jButton_Modificar_Actividad.setText("Modificar Actividad");
        jButton_Modificar_Actividad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));
        jButton_Modificar_Actividad.setMaximumSize(new java.awt.Dimension(125, 27));
        jButton_Modificar_Actividad.setMinimumSize(new java.awt.Dimension(125, 27));
        jButton_Modificar_Actividad.setPreferredSize(new java.awt.Dimension(125, 27));
        jButton_Modificar_Actividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Modificar_ActividadActionPerformed(evt);
            }
        });

        jButton_Eliminar_Actividad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Eliminar_Actividad.setForeground(new java.awt.Color(255, 0, 0));
        jButton_Eliminar_Actividad.setText("Eliminar Actividad");
        jButton_Eliminar_Actividad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));
        jButton_Eliminar_Actividad.setMaximumSize(new java.awt.Dimension(125, 27));
        jButton_Eliminar_Actividad.setMinimumSize(new java.awt.Dimension(125, 27));
        jButton_Eliminar_Actividad.setPreferredSize(new java.awt.Dimension(125, 27));
        jButton_Eliminar_Actividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Eliminar_ActividadActionPerformed(evt);
            }
        });

        label_Estado_Actividad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Estado_Actividad.setForeground(new java.awt.Color(255, 0, 0));
        label_Estado_Actividad.setText("Estado de la actividad");

        estado_Actividad_Indicador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        estado_Actividad_Indicador.setForeground(new java.awt.Color(0, 153, 51));
        estado_Actividad_Indicador.setText("--");

        jDate_fecha_final.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jDate_fecha_inicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        label_Fecha_Inicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Fecha_Inicio.setText("Fecha de inicio");

        jLabel_Fecha_Final.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Fecha_Final.setText("Fecha Final");

        textArea_Descripcion.setColumns(20);
        textArea_Descripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textArea_Descripcion.setRows(5);
        jScrollPane_Descripcion.setViewportView(textArea_Descripcion);

        textField_Nombre_Actividad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        label_Descripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Descripcion.setText("Descripción");

        label_Nombre_Actividad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Nombre_Actividad.setText("Nombre");

        jButton_Iniciar_Actividad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Iniciar_Actividad.setForeground(new java.awt.Color(0, 204, 51));
        jButton_Iniciar_Actividad.setText("Inicar Actividad");
        jButton_Iniciar_Actividad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));
        jButton_Iniciar_Actividad.setMaximumSize(new java.awt.Dimension(125, 27));
        jButton_Iniciar_Actividad.setMinimumSize(new java.awt.Dimension(125, 27));
        jButton_Iniciar_Actividad.setPreferredSize(new java.awt.Dimension(125, 27));
        jButton_Iniciar_Actividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Iniciar_ActividadActionPerformed(evt);
            }
        });

        jButton_Atras.setBackground(new java.awt.Color(102, 0, 102));
        jButton_Atras.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton_Atras.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Atras.setText("ATRAS");
        jButton_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AtrasActionPerformed(evt);
            }
        });

        consultar_tareas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        consultar_tareas.setText("Consultar Tareas ->");
        consultar_tareas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));
        consultar_tareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_tareasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ActividadesLayout = new javax.swing.GroupLayout(panel_Actividades);
        panel_Actividades.setLayout(panel_ActividadesLayout);
        panel_ActividadesLayout.setHorizontalGroup(
            panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ActividadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_Descripcion)
                    .addComponent(textField_Nombre_Actividad)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ActividadesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Eliminar_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ActividadesLayout.createSequentialGroup()
                        .addGroup(panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Fecha_Final)
                            .addComponent(jDate_fecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDate_fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_Fecha_Inicio)
                            .addComponent(labelActividades)
                            .addComponent(label_Descripcion)
                            .addComponent(label_Nombre_Actividad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ActividadesLayout.createSequentialGroup()
                                .addGroup(panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_Estado_Actividad)
                                    .addComponent(estado_Actividad_Indicador, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90))
                            .addComponent(jButton_Iniciar_Actividad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_ActividadesLayout.createSequentialGroup()
                        .addGroup(panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_ActividadesLayout.createSequentialGroup()
                                .addComponent(jButton_Modificar_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(consultar_tareas, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_Atras))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_ActividadesLayout.setVerticalGroup(
            panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ActividadesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelActividades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Nombre_Actividad)
                .addGap(5, 5, 5)
                .addComponent(textField_Nombre_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(label_Descripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_ActividadesLayout.createSequentialGroup()
                        .addComponent(label_Fecha_Inicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDate_fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_ActividadesLayout.createSequentialGroup()
                        .addComponent(label_Estado_Actividad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estado_Actividad_Indicador)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Fecha_Final)
                .addGap(11, 11, 11)
                .addGroup(panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDate_fecha_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Iniciar_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultar_tareas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Modificar_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jButton_Eliminar_Actividad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_Tareas.setBackground(new java.awt.Color(255, 255, 255));

        labelTareas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTareas.setText("Tareas");

        lista_tareas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lista_tareas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_tareasValueChanged(evt);
            }
        });
        panel__Lista_Tareas.setViewportView(lista_tareas);

        label_Nombre_Tarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Nombre_Tarea.setText("Nombre");

        textField_Nombre_Tarea.setEditable(false);
        textField_Nombre_Tarea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        label_Equipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Equipo.setText("Equipo");

        jLabel_Responsable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Responsable.setText("Responsable");

        label_Fecha_Maxima_Realizacion_Tarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Fecha_Maxima_Realizacion_Tarea.setText("Fecha Maxima Realizacion");

        label_Fecha_Finalizacion_Real_Tarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Fecha_Finalizacion_Real_Tarea.setText("Fecha Finalizacion Real");

        jButton_Modificar_Tarea.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Modificar_Tarea.setForeground(new java.awt.Color(0, 0, 255));
        jButton_Modificar_Tarea.setText("Editar Tarea");
        jButton_Modificar_Tarea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));
        jButton_Modificar_Tarea.setMaximumSize(new java.awt.Dimension(125, 27));
        jButton_Modificar_Tarea.setMinimumSize(new java.awt.Dimension(125, 27));
        jButton_Modificar_Tarea.setPreferredSize(new java.awt.Dimension(125, 27));
        jButton_Modificar_Tarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Modificar_TareaActionPerformed(evt);
            }
        });

        jButton_Eliminar_Tarea.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Eliminar_Tarea.setForeground(new java.awt.Color(255, 0, 0));
        jButton_Eliminar_Tarea.setText("Eliminar Tarea");
        jButton_Eliminar_Tarea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));
        jButton_Eliminar_Tarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Eliminar_TareaActionPerformed(evt);
            }
        });

        jButton_Crear_Tarea_Nueva.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Crear_Tarea_Nueva.setForeground(new java.awt.Color(0, 204, 51));
        jButton_Crear_Tarea_Nueva.setText("Crear Tarea Nueva");
        jButton_Crear_Tarea_Nueva.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 1, true));
        jButton_Crear_Tarea_Nueva.setMaximumSize(new java.awt.Dimension(125, 27));
        jButton_Crear_Tarea_Nueva.setMinimumSize(new java.awt.Dimension(125, 27));
        jButton_Crear_Tarea_Nueva.setPreferredSize(new java.awt.Dimension(125, 27));
        jButton_Crear_Tarea_Nueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Crear_Tarea_NuevaActionPerformed(evt);
            }
        });

        textField_Equipo.setEditable(false);
        textField_Equipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textField_Responsable.setEditable(false);
        textField_Responsable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textField_FechaMax.setEditable(false);
        textField_FechaMax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textField_FechaFinTarea.setEditable(false);
        textField_FechaFinTarea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        label_Estado_Tarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Estado_Tarea.setForeground(new java.awt.Color(255, 0, 51));
        label_Estado_Tarea.setText("Estado de la Tarea");

        estado_Tarea_Indicador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        estado_Tarea_Indicador.setForeground(new java.awt.Color(0, 153, 51));
        estado_Tarea_Indicador.setText("--");

        javax.swing.GroupLayout panel_TareasLayout = new javax.swing.GroupLayout(panel_Tareas);
        panel_Tareas.setLayout(panel_TareasLayout);
        panel_TareasLayout.setHorizontalGroup(
            panel_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TareasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panel_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel__Lista_Tareas)
                    .addGroup(panel_TareasLayout.createSequentialGroup()
                        .addComponent(labelTareas)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_TareasLayout.createSequentialGroup()
                        .addGroup(panel_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_Nombre_Tarea)
                            .addComponent(label_Fecha_Finalizacion_Real_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(label_Fecha_Maxima_Realizacion_Tarea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textField_FechaMax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textField_FechaFinTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField_Nombre_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Crear_Tarea_Nueva, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Modificar_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_TareasLayout.createSequentialGroup()
                                .addGroup(panel_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_Equipo)
                                    .addComponent(jLabel_Responsable)
                                    .addComponent(label_Estado_Tarea)
                                    .addComponent(estado_Tarea_Indicador, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_TareasLayout.createSequentialGroup()
                                .addGroup(panel_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton_Eliminar_Tarea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textField_Responsable, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textField_Equipo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(27, 27, 27))))))
        );
        panel_TareasLayout.setVerticalGroup(
            panel_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_TareasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTareas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_TareasLayout.createSequentialGroup()
                        .addComponent(panel__Lista_Tareas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(label_Nombre_Tarea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_Nombre_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(label_Fecha_Maxima_Realizacion_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_FechaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_TareasLayout.createSequentialGroup()
                        .addComponent(label_Equipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Responsable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_Responsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(panel_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_TareasLayout.createSequentialGroup()
                        .addComponent(label_Fecha_Finalizacion_Real_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_FechaFinTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_TareasLayout.createSequentialGroup()
                        .addComponent(label_Estado_Tarea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(estado_Tarea_Indicador)))
                .addGap(44, 44, 44)
                .addComponent(jButton_Crear_Tarea_Nueva, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panel_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Modificar_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Eliminar_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_Actividades_EquiposLayout = new javax.swing.GroupLayout(jPanel_Actividades_Equipos);
        jPanel_Actividades_Equipos.setLayout(jPanel_Actividades_EquiposLayout);
        jPanel_Actividades_EquiposLayout.setHorizontalGroup(
            jPanel_Actividades_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Actividades_EquiposLayout.createSequentialGroup()
                .addComponent(panel_Actividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_Tareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Actividades_EquiposLayout.setVerticalGroup(
            jPanel_Actividades_EquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Actividades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_Tareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Actividades_Equipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Actividades_Equipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Iniciar_ActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Iniciar_ActividadActionPerformed
        // 8.- DIOS Iniciar Actividad
        this.personalDeCoordinacion.iniciarActividad();
        JOptionPane.showMessageDialog(this, "Actividad y Tareas ! iniciadas En Curso !");
        irAnteriorConRecarga();
    }//GEN-LAST:event_jButton_Iniciar_ActividadActionPerformed

    private void jButton_Eliminar_ActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Eliminar_ActividadActionPerformed
        // 9.- DIOS Eliminar Actividad
        if(! this.personalDeCoordinacion.eliminarActividad() )
            JOptionPane.showMessageDialog(this, "Actividad en Curso, no se puede eliminar. Trabajatela !!");
        irAnteriorConRecarga();
    }//GEN-LAST:event_jButton_Eliminar_ActividadActionPerformed

    private void jButton_Modificar_ActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Modificar_ActividadActionPerformed
        // 8.- DIOS Modifica la actividad
        if(! this.personalDeCoordinacion.modificarActividad(
            this.textField_Nombre_Actividad.getText(),
            this.textArea_Descripcion.getText(),
            this.jDate_fecha_inicio.getDate(),
            this.jDate_fecha_final.getDate()
        ) )
            JOptionPane.showMessageDialog(this, "Actividad en Curso, no se puede modificar. Trabajatela !!");
    }//GEN-LAST:event_jButton_Modificar_ActividadActionPerformed

    private void jButton_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AtrasActionPerformed
        vAnterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_AtrasActionPerformed

    private void lista_tareasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_tareasValueChanged
        int index = this.lista_tareas.getSelectedIndex();
        if(index > -1){
            Object tarea = this.tareas.get(index);
            DetallesTarea detalles = this.personalDeCoordinacion.consultarDetallesTarea(tarea);
            
            this.textField_Nombre_Tarea.setText(detalles.nombre);
            this.textField_FechaMax.setText(formato.format(detalles.fechaMaxRealizacion));
            if(detalles.fechaFinalizacionReal != null)
                this.textField_FechaFinTarea.setText(formato.format(detalles.fechaFinalizacionReal));
            else
                this.textField_FechaFinTarea.setText(" - - ");
            this.estado_Tarea_Indicador.setText(detalles.estadoTarea);
            this.textField_Equipo.setText(detalles.equipo.toString());
            this.textField_Responsable.setText(detalles.responsable.toString());
        } else{
            this.textField_Nombre_Tarea.setText("");
            this.textField_FechaFinTarea.setText("");
            this.textField_FechaMax.setText("");
            this.estado_Tarea_Indicador.setText(" - - ");
            this.textField_Equipo.setText("");
            this.textField_Responsable.setText("");
        }
    }//GEN-LAST:event_lista_tareasValueChanged

    private void jButton_Modificar_TareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Modificar_TareaActionPerformed
        int index = this.lista_tareas.getSelectedIndex();
        if(index != -1){
            Object tarea = tareas.get(index);
            
            Vista_3_Tarea_Editar vista_Tarea_Editar = new Vista_3_Tarea_Editar( this.personalDeCoordinacion, this, tarea, this.personalDeCoordinacion.consultarDetallesTarea(tarea) );
            this.setVisible(false);
            vista_Tarea_Editar.setVisible(true);
        } else
            JOptionPane.showMessageDialog(this, "Selecciona 1 Tarea para Modificar");
    }//GEN-LAST:event_jButton_Modificar_TareaActionPerformed

    private void jButton_Eliminar_TareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Eliminar_TareaActionPerformed
        int index = this.lista_tareas.getSelectedIndex();
        if(index != -1) {
            Object tarea = this.detallesActividad.tareas.get(index);
            this.personalDeCoordinacion.eliminarTarea(tarea);
            this.actualizarListaTareas();
            JOptionPane.showMessageDialog(this, "Eliminando Tarea '" + tarea.toString() + "'. Tareas En Cruso no serán eliminadas");
        } else
            JOptionPane.showMessageDialog(this, "Selecciona 1 Tarea para Eliminar");
    }//GEN-LAST:event_jButton_Eliminar_TareaActionPerformed

    private void jButton_Crear_Tarea_NuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Crear_Tarea_NuevaActionPerformed
        Vista_3_Tarea_Nueva vista_Tarea_Nueva = new Vista_3_Tarea_Nueva(personalDeCoordinacion, this);
        vista_Tarea_Nueva.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_Crear_Tarea_NuevaActionPerformed

    private void consultar_tareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_tareasActionPerformed
        this.panel_Tareas.setVisible(true);
        
        DefaultListModel modeloLista = new DefaultListModel();
        this.tareas = this.detallesActividad.tareas;
        for(Object tarea: this.tareas)
            modeloLista.addElement(tarea);
        this.lista_tareas.setModel(modeloLista);
    }//GEN-LAST:event_consultar_tareasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultar_tareas;
    private javax.swing.JLabel estado_Actividad_Indicador;
    private javax.swing.JLabel estado_Tarea_Indicador;
    private javax.swing.JButton jButton_Atras;
    private javax.swing.JButton jButton_Crear_Tarea_Nueva;
    private javax.swing.JButton jButton_Eliminar_Actividad;
    private javax.swing.JButton jButton_Eliminar_Tarea;
    private javax.swing.JButton jButton_Iniciar_Actividad;
    private javax.swing.JButton jButton_Modificar_Actividad;
    private javax.swing.JButton jButton_Modificar_Tarea;
    private com.toedter.calendar.JDateChooser jDate_fecha_final;
    private com.toedter.calendar.JDateChooser jDate_fecha_inicio;
    private javax.swing.JLabel jLabel_Fecha_Final;
    private javax.swing.JLabel jLabel_Responsable;
    private javax.swing.JPanel jPanel_Actividades_Equipos;
    private javax.swing.JScrollPane jScrollPane_Descripcion;
    private javax.swing.JLabel labelActividades;
    private javax.swing.JLabel labelTareas;
    private javax.swing.JLabel label_Descripcion;
    private javax.swing.JLabel label_Equipo;
    private javax.swing.JLabel label_Estado_Actividad;
    private javax.swing.JLabel label_Estado_Tarea;
    private javax.swing.JLabel label_Fecha_Finalizacion_Real_Tarea;
    private javax.swing.JLabel label_Fecha_Inicio;
    private javax.swing.JLabel label_Fecha_Maxima_Realizacion_Tarea;
    private javax.swing.JLabel label_Nombre_Actividad;
    private javax.swing.JLabel label_Nombre_Tarea;
    private javax.swing.JList<String> lista_tareas;
    private javax.swing.JPanel panel_Actividades;
    private javax.swing.JPanel panel_Tareas;
    private javax.swing.JScrollPane panel__Lista_Tareas;
    private javax.swing.JTextArea textArea_Descripcion;
    private javax.swing.JTextField textField_Equipo;
    private javax.swing.JTextField textField_FechaFinTarea;
    private javax.swing.JTextField textField_FechaMax;
    private javax.swing.JTextField textField_Nombre_Actividad;
    private javax.swing.JTextField textField_Nombre_Tarea;
    private javax.swing.JTextField textField_Responsable;
    // End of variables declaration//GEN-END:variables

    /*
    private void vaciar(JList<String> lista) {
        lista.setModel(new DefaultListModel());
    }
*/
    public void actualizarListaTareas() {
        DefaultListModel modeloLista = new DefaultListModel();
       
        ArrayList tareas = this.personalDeCoordinacion.consultarTareas();
        for (Object tarea: tareas) {
            String nombre = this.personalDeCoordinacion.consultarDetallesTarea(tarea).nombre;
            modeloLista.addElement(nombre);
        }
        lista_tareas.setModel(modeloLista);
    }
    
    /*
    // obtener miembros del equipo seleccionado y poner en la lista de responsables
    private void actualizarMiembrosEquipo(Object equipo) {
        ArrayList miembros = personalDeCoordinacion.consultarMiembrosDelEquipo(equipo);
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        for(Object miembro: miembros){
            String nombre = personalDeCoordinacion.getNombrePersProy(miembro);
            dcbm.addElement(nombre);
        }
        this.comboBox_Responsable.setModel(dcbm);
    }
    */
    
    
    
    
    // NUEVO NO BORRAR
    /*
    // Llena el ComboBox con el contenido del arraylist
    private void carga_combos(JComboBox<String> comboBox, ArrayList array) {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for(Object object: array){
            modelo.addElement(object);
        }
        comboBox.setModel(modelo);
    }
    */

    // Va a la ventana anterior, y volviendo a cargar las actividades
    private void irAnteriorConRecarga() {
        Vista_2_Actividad_Listado vActividades =(Vista_2_Actividad_Listado) this.vAnterior;
        vActividades.refrescar_lista_actividades();
        vAnterior.setVisible(true);
        this.setVisible(false);
    }

    // Muestra el objeto en el combBox (v2.0.0 - v2.0.1)
    private void muestra(JComboBox<String> comboBox, Object obj) {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement(obj);
        comboBox.setModel(modelo);
    }
    
    // Se ejecuta cada vez que se crea la tarea con éxito
    public void altaTarea(Object tarea){
        DefaultListModel modelo = (DefaultListModel) lista_tareas.getModel();
        modelo.addElement(tarea);
        lista_tareas.setModel(modelo);
        
        lista_tareas.setSelectedIndex(lista_tareas.getMaxSelectionIndex());
    }
    
}
