package vista;

import controlador.PersonalDeCoordinacion;
import javax.swing.JFrame;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import data.DetallesTarea;
import controlador.PersonalDeProyecto;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

public class Vista_3_Tareas_Asignadas extends javax.swing.JFrame
{
    final ArrayList tareas;
    private javax.swing.JFrame vAnterior;
    private PersonalDeProyecto personalDeProyecto;
    private SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
    
    public Vista_3_Tareas_Asignadas(PersonalDeProyecto personalDeProyecto, JFrame vAnterior) {
        initComponents();
        jPanel_Detalles_Tarea.setVisible(false);
        this.personalDeProyecto = personalDeProyecto;
        this.vAnterior = vAnterior;
        
        tareas = this.personalDeProyecto.consultarTareasAsignadas();
        DefaultListModel listModel = new DefaultListModel();
        for(Object tarea: tareas){
            listModel.addElement(tarea);
        }
        this.lista_tareas.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Tareas_Asignadas = new javax.swing.JPanel();
        jPanel_Listado_Tareas = new javax.swing.JPanel();
        listado_tareas_asignadas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_tareas = new javax.swing.JList<>();
        jButton_consultar = new javax.swing.JButton();
        JButton_atras = new javax.swing.JButton();
        jPanel_Detalles_Tarea = new javax.swing.JPanel();
        datos_tarea = new javax.swing.JTextField();
        jLabel_nombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel_fecha_maxima = new javax.swing.JLabel();
        fecha_maxima_realizacion = new javax.swing.JTextField();
        jLabel_fecha_fin_real = new javax.swing.JLabel();
        fecha_finalizacion_real = new javax.swing.JTextField();
        jLabel_equipo = new javax.swing.JLabel();
        equipo = new javax.swing.JTextField();
        jLabel_responsable = new javax.swing.JLabel();
        responsable = new javax.swing.JTextField();
        estado_label = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        finalizar_tarea_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listado de Tareas Asignadas");
        setResizable(false);

        jPanel_Tareas_Asignadas.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_Tareas_Asignadas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel_Listado_Tareas.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_Listado_Tareas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        listado_tareas_asignadas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        listado_tareas_asignadas.setText("Listado de Tareas Asignadas");

        lista_tareas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lista_tareas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_tareasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista_tareas);

        jButton_consultar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_consultar.setText("Consultar ->");
        jButton_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consultarActionPerformed(evt);
            }
        });

        JButton_atras.setBackground(new java.awt.Color(102, 0, 102));
        JButton_atras.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JButton_atras.setForeground(new java.awt.Color(255, 255, 255));
        JButton_atras.setText("ATRÁS");
        JButton_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Listado_TareasLayout = new javax.swing.GroupLayout(jPanel_Listado_Tareas);
        jPanel_Listado_Tareas.setLayout(jPanel_Listado_TareasLayout);
        jPanel_Listado_TareasLayout.setHorizontalGroup(
            jPanel_Listado_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Listado_TareasLayout.createSequentialGroup()
                .addGroup(jPanel_Listado_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Listado_TareasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_consultar))
                    .addGroup(jPanel_Listado_TareasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_Listado_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_Listado_TareasLayout.createSequentialGroup()
                                .addGroup(jPanel_Listado_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(listado_tareas_asignadas)
                                    .addComponent(JButton_atras))
                                .addGap(0, 213, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel_Listado_TareasLayout.setVerticalGroup(
            jPanel_Listado_TareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Listado_TareasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listado_tareas_asignadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(jButton_consultar)
                .addGap(4, 4, 4)
                .addComponent(JButton_atras)
                .addContainerGap())
        );

        jPanel_Detalles_Tarea.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Detalles_Tarea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        datos_tarea.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        datos_tarea.setText("Datos Tarea");
        datos_tarea.setBorder(null);

        jLabel_nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_nombre.setText("Nombre");

        nombre.setEditable(false);
        nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel_fecha_maxima.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_fecha_maxima.setText("Fecha Máxima realizacion");

        fecha_maxima_realizacion.setEditable(false);
        fecha_maxima_realizacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel_fecha_fin_real.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_fecha_fin_real.setText("Fecha finalizacion Real");

        fecha_finalizacion_real.setEditable(false);
        fecha_finalizacion_real.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel_equipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_equipo.setText("Equipo");

        equipo.setEditable(false);
        equipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel_responsable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_responsable.setText("Responsable");

        responsable.setEditable(false);
        responsable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        estado_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        estado_label.setForeground(new java.awt.Color(0, 0, 255));
        estado_label.setText("Estado Tarea");

        estado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        estado.setForeground(new java.awt.Color(0, 204, 51));
        estado.setText(" - - ");

        finalizar_tarea_jButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        finalizar_tarea_jButton.setText("Finalizar tarea");
        finalizar_tarea_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizar_tarea_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Detalles_TareaLayout = new javax.swing.GroupLayout(jPanel_Detalles_Tarea);
        jPanel_Detalles_Tarea.setLayout(jPanel_Detalles_TareaLayout);
        jPanel_Detalles_TareaLayout.setHorizontalGroup(
            jPanel_Detalles_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Detalles_TareaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Detalles_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Detalles_TareaLayout.createSequentialGroup()
                        .addGroup(jPanel_Detalles_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_responsable, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(jLabel_equipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estado_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel_Detalles_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(responsable)
                            .addComponent(equipo)
                            .addGroup(jPanel_Detalles_TareaLayout.createSequentialGroup()
                                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 15, Short.MAX_VALUE))))
                    .addGroup(jPanel_Detalles_TareaLayout.createSequentialGroup()
                        .addGroup(jPanel_Detalles_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_fecha_maxima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_fecha_fin_real, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel_Detalles_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha_finalizacion_real)
                            .addComponent(fecha_maxima_realizacion)))
                    .addGroup(jPanel_Detalles_TareaLayout.createSequentialGroup()
                        .addComponent(datos_tarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_Detalles_TareaLayout.createSequentialGroup()
                        .addComponent(jLabel_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(nombre)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Detalles_TareaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finalizar_tarea_jButton)
                .addGap(179, 179, 179))
        );
        jPanel_Detalles_TareaLayout.setVerticalGroup(
            jPanel_Detalles_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Detalles_TareaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datos_tarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel_Detalles_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Detalles_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_fecha_maxima)
                    .addComponent(fecha_maxima_realizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Detalles_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_fecha_fin_real)
                    .addComponent(fecha_finalizacion_real, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Detalles_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_equipo)
                    .addComponent(equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Detalles_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_responsable)
                    .addComponent(responsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Detalles_TareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estado_label)
                    .addComponent(estado))
                .addGap(79, 79, 79)
                .addComponent(finalizar_tarea_jButton)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_Tareas_AsignadasLayout = new javax.swing.GroupLayout(jPanel_Tareas_Asignadas);
        jPanel_Tareas_Asignadas.setLayout(jPanel_Tareas_AsignadasLayout);
        jPanel_Tareas_AsignadasLayout.setHorizontalGroup(
            jPanel_Tareas_AsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Tareas_AsignadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Listado_Tareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Detalles_Tarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_Tareas_AsignadasLayout.setVerticalGroup(
            jPanel_Tareas_AsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Tareas_AsignadasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Tareas_AsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Detalles_Tarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Listado_Tareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1151, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Tareas_Asignadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Tareas_Asignadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_atrasActionPerformed
        vAnterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JButton_atrasActionPerformed

    private void finalizar_tarea_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizar_tarea_jButtonActionPerformed
        //Date fechaFinalizacionReal = Calendar.getInstance().getTime();
        int index = this.lista_tareas.getSelectedIndex();
        if(index != -1){
            Object tarea = this.tareas.get(index);
            
            this.personalDeProyecto.finalizarTarea();
            JOptionPane.showMessageDialog(this, "Si la Tarea estaba En Curso,\nla Tarea '" + tarea.toString() + "' se habrá finalizado");
            limpiar_panel_detalles();
        } else
            JOptionPane.showMessageDialog(this, "Selecciona 1 Tarea");
    }//GEN-LAST:event_finalizar_tarea_jButtonActionPerformed

    private void jButton_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consultarActionPerformed
        int index = this.lista_tareas.getSelectedIndex();
        if(index != -1){
            Object tarea = this.tareas.get(index);
            DetallesTarea detallesTarea = this.personalDeProyecto.consultarDetallesTarea(tarea);
            
            rellenarDetallesTarea(detallesTarea);
            jPanel_Detalles_Tarea.setVisible(true);
            finalizar_tarea_jButton.setEnabled(true);
        } else
            JOptionPane.showMessageDialog(this, "Selecciona 1 Tarea");
    }//GEN-LAST:event_jButton_consultarActionPerformed

    private void lista_tareasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_tareasValueChanged
        limpiar_panel_detalles();
    }//GEN-LAST:event_lista_tareasValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_atras;
    private javax.swing.JTextField datos_tarea;
    private javax.swing.JTextField equipo;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel estado_label;
    private javax.swing.JTextField fecha_finalizacion_real;
    private javax.swing.JTextField fecha_maxima_realizacion;
    private javax.swing.JButton finalizar_tarea_jButton;
    private javax.swing.JButton jButton_consultar;
    private javax.swing.JLabel jLabel_equipo;
    private javax.swing.JLabel jLabel_fecha_fin_real;
    private javax.swing.JLabel jLabel_fecha_maxima;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_responsable;
    private javax.swing.JPanel jPanel_Detalles_Tarea;
    private javax.swing.JPanel jPanel_Listado_Tareas;
    private javax.swing.JPanel jPanel_Tareas_Asignadas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista_tareas;
    private javax.swing.JLabel listado_tareas_asignadas;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField responsable;
    // End of variables declaration//GEN-END:variables

    
    public void limpiar_panel_detalles() {
        this.nombre.setText("");
        this.fecha_maxima_realizacion.setText("");
        this.fecha_finalizacion_real.setText("");
        this.equipo.setText("");
        this.responsable.setText("");
        this.estado.setText(" - - ");
        finalizar_tarea_jButton.setEnabled(false);
    }
    
    public void rellenarDetallesTarea(DetallesTarea detallesTarea) {
        nombre.setText(detallesTarea.nombre);
        equipo.setText(detallesTarea.equipo.toString());
        responsable.setText(detallesTarea.responsable.toString());
        fecha_maxima_realizacion.setText(formato.format(detallesTarea.fechaMaxRealizacion));
        estado.setText(detallesTarea.estadoTarea);
        if(detallesTarea.fechaFinalizacionReal != null)
            this.fecha_finalizacion_real.setText(formato.format(detallesTarea.fechaFinalizacionReal));
        else
            this.fecha_finalizacion_real.setText(" - - ");
    }
}
