package vista;

import javax.swing.JFrame;
import controlador.PersonalDeCoordinacion;

public class Vista_Equipos extends javax.swing.JFrame {

    public Vista_Equipos(PersonalDeCoordinacion personalDeCoordinacion, JFrame vAnterior) {
        initComponents();
        
        this.personalDeCoordinacion = personalDeCoordinacion;
        this.vAnterior = vAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_listaEquipos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_lista_equipos = new javax.swing.JList<>();
        jLabel_lista_equipos = new java.awt.Label();
        jButton_consultarEquipo = new javax.swing.JButton();
        jButton_CrearEquipo = new javax.swing.JButton();
        jButton_atras = new javax.swing.JButton();
        jPanel_datosEquipo = new javax.swing.JPanel();
        jLabel_nombreEquipo = new javax.swing.JLabel();
        jTextField_nombreEquipo = new javax.swing.JTextField();
        jLabel_miembros_equipo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_miembrosEquipo = new javax.swing.JList<>();
        jBoton_eliminarMiembro = new javax.swing.JButton();
        jButton_aniadirMiembro = new javax.swing.JButton();
        jButton_eliminarEquipo = new javax.swing.JButton();
        jButton_modificarEquipo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_miembrosProyecto = new javax.swing.JList<>();
        jLabel_miembrosProyectos = new javax.swing.JLabel();
        jLabel_datos_equipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equipos");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel_listaEquipos.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_listaEquipos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jList_lista_equipos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jList_lista_equipos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Movistar", "Aenor", "ATHENA" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList_lista_equipos);

        jLabel_lista_equipos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_lista_equipos.setText("LISTA DE EQUIPOS");

        jButton_consultarEquipo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_consultarEquipo.setText("Consultar Equipo");

        jButton_CrearEquipo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_CrearEquipo.setText("Crear Equipo");

        jButton_atras.setBackground(new java.awt.Color(102, 0, 102));
        jButton_atras.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton_atras.setForeground(new java.awt.Color(255, 255, 255));
        jButton_atras.setText("ATRÁS");
        jButton_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_listaEquiposLayout = new javax.swing.GroupLayout(jPanel_listaEquipos);
        jPanel_listaEquipos.setLayout(jPanel_listaEquiposLayout);
        jPanel_listaEquiposLayout.setHorizontalGroup(
            jPanel_listaEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listaEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_listaEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel_listaEquiposLayout.createSequentialGroup()
                        .addGroup(jPanel_listaEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_lista_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_listaEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton_CrearEquipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_consultarEquipo, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jButton_atras))
                        .addGap(0, 148, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_listaEquiposLayout.setVerticalGroup(
            jPanel_listaEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_listaEquiposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_lista_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_consultarEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_CrearEquipo)
                .addGap(64, 64, 64)
                .addComponent(jButton_atras)
                .addGap(68, 68, 68))
        );

        jPanel_datosEquipo.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_datosEquipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_nombreEquipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_nombreEquipo.setText("Nombre");

        jLabel_miembros_equipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_miembros_equipo.setText("Miembros en el Equipo");

        jList_miembrosEquipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jList_miembrosEquipo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Jorge Cremades, jorgito25@gmail.com, 666444999", "Jorge Gandia, g.jorge@gmail.com, 666555999", "Aroa Sanchez, jorgito25@hotmail.com, 666666999" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList_miembrosEquipo);

        jBoton_eliminarMiembro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBoton_eliminarMiembro.setText("Eliminar Miembro de Equipo");

        jButton_aniadirMiembro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_aniadirMiembro.setText("Añadir Miembro a Equipo");

        jButton_eliminarEquipo.setBackground(new java.awt.Color(255, 255, 255));
        jButton_eliminarEquipo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_eliminarEquipo.setText("Eliminar Equipo");

        jButton_modificarEquipo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_modificarEquipo.setText("Modificar Equipo");

        jList_miembrosProyecto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jList_miembrosProyecto.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Román Aranjuez, roman.aranjuez@gmail.com, 689675123", "Juajo Valverde, juanjo.valverde@gmail.com, 668678547", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList_miembrosProyecto);

        jLabel_miembrosProyectos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_miembrosProyectos.setText("Miembros de Proyecto");

        jLabel_datos_equipo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_datos_equipo.setText("DATOS DEL EQUIPO");

        javax.swing.GroupLayout jPanel_datosEquipoLayout = new javax.swing.GroupLayout(jPanel_datosEquipo);
        jPanel_datosEquipo.setLayout(jPanel_datosEquipoLayout);
        jPanel_datosEquipoLayout.setHorizontalGroup(
            jPanel_datosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_datosEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_datosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_datosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton_eliminarEquipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_modificarEquipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_miembrosProyectos)
                    .addComponent(jButton_aniadirMiembro, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_datosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                        .addComponent(jBoton_eliminarMiembro, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_datos_equipo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_nombreEquipo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_miembros_equipo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_nombreEquipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel_datosEquipoLayout.setVerticalGroup(
            jPanel_datosEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_datosEquipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_datos_equipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_nombreEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_miembros_equipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBoton_eliminarMiembro)
                .addGap(18, 18, 18)
                .addComponent(jLabel_miembrosProyectos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_aniadirMiembro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_modificarEquipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_eliminarEquipo)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_listaEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_datosEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_datosEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_listaEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 599, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1146, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atrasActionPerformed
        vAnterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_atrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBoton_eliminarMiembro;
    private javax.swing.JButton jButton_CrearEquipo;
    private javax.swing.JButton jButton_aniadirMiembro;
    private javax.swing.JButton jButton_atras;
    private javax.swing.JButton jButton_consultarEquipo;
    private javax.swing.JButton jButton_eliminarEquipo;
    private javax.swing.JButton jButton_modificarEquipo;
    private javax.swing.JLabel jLabel_datos_equipo;
    private java.awt.Label jLabel_lista_equipos;
    private javax.swing.JLabel jLabel_miembrosProyectos;
    private javax.swing.JLabel jLabel_miembros_equipo;
    private javax.swing.JLabel jLabel_nombreEquipo;
    private javax.swing.JList<String> jList_lista_equipos;
    private javax.swing.JList<String> jList_miembrosEquipo;
    private javax.swing.JList<String> jList_miembrosProyecto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_datosEquipo;
    private javax.swing.JPanel jPanel_listaEquipos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField_nombreEquipo;
    // End of variables declaration//GEN-END:variables

    private PersonalDeCoordinacion personalDeCoordinacion;
    private javax.swing.JFrame vAnterior;
}
